name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to registry
      uses: docker/login-action@v2
      with:
        registry: docker.cheesyphoenix.tk
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    -
      name: Build and push API docker image
      uses: docker/build-push-action@v3
      with:
        context: ./scraper-api
        file: ./dockerfile
        push: true
        tags: docker.cheesyphoenix.tk/cheesyphoenix/betterschool-api:latest
    
    -
      name: Build and push WEB docker image
      uses: docker/build-push-action@v3
      with:
        context: ./BetterSchool-Frontend
        file: ./dockerfile
        push: true
        tags: docker.cheesyphoenix.tk/cheesyphoenix/betterschool-web:latest
        
